/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;




@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-06-04T14:58:39.313Z")

@Validated
@Api(value = "login", description = "the login API")
@RequestMapping(value = "")
public interface LoginApi {

    @ApiOperation(value = "Where all users can login", nickname = "login", notes = "This is all accounts", tags={ "login", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful login"),
        @ApiResponse(code = 400, message = "Invalid username or password supplied") })
    @RequestMapping(value = "/login",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> login();

}
