/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Project;
import io.swagger.model.Ticket;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-06-04T14:58:39.313Z")

@Validated
@Api(value = "technician", description = "the technician API")
@RequestMapping(value = "")
public interface TechnicianApi {

    @ApiOperation(value = "Delete ticket by ID", nickname = "deleteTicketTechnician", notes = "For valid response try integer IDs with positive integer value.         Negative or non-integer values will generate API errors", tags={ "technician", })
    // @ApiResponses(value = { 
    //     @ApiResponse(code = 200, message = "Ticket was deleted successfully"),
    //     @ApiResponse(code = 400, message = "Invalid ID supplied"),
    //     @ApiResponse(code = 404, message = "ticket not found") })
    // @RequestMapping(value = "/technician/project/ticket/{ticketId}",
    //     produces = { "application/xml", "application/json" }, 
    //     method = RequestMethod.DELETE)
    @DeleteMapping("/helpdesk/project/ticket/{ticketId}")
    ResponseEntity<Void> deleteTicketTechnician(@RequestParam Integer id);


    @ApiOperation(value = "Find issue tickets by ID", nickname = "getIssueTicketById", notes = "For valid response try integer IDs with value >= 1 and <= 10.         Other values will generated exceptions", response = Ticket.class, tags={ "technician", })
    // @ApiResponses(value = { 
    //     @ApiResponse(code = 200, message = "successful operation", response = Ticket.class),
    //     @ApiResponse(code = 400, message = "Invalid ID supplied"),
    //     @ApiResponse(code = 404, message = "ticket not found") })
    // @RequestMapping(value = "/technician/project/ticket/{ticketId}",
    //     produces = { "application/xml", "application/json" }, 
    //     method = RequestMethod.GET)
    @GetMapping(path="/technician/project/ticket/{ticketId}")
    Iterable<Ticket> getIssueTicketById(@RequestParam Integer id, @RequestParam Integer Project_id);


    @ApiOperation(value = "Get tickets that are issues", nickname = "getIssues", notes = "Gets a list of all the tickets that are issues", response = Ticket.class, tags={ "technician", })
    // @ApiResponses(value = { 
    //     @ApiResponse(code = 200, message = "successful operation", response = Ticket.class),
    //     @ApiResponse(code = 400, message = "Invalid ID supplied"),
    //     @ApiResponse(code = 404, message = "ticket not found") })
    // @RequestMapping(value = "/technician/project/tickets",
    //     produces = { "application/xml", "application/json" }, 
    //     method = RequestMethod.GET)
    @GetMapping(path="/technician/project/tickets")
    Iterable<Ticket> getIssues(@RequestParam Integer Project_id);


    @ApiOperation(value = "Get all projects", nickname = "getProjectsTechnician", notes = "Gets a list of all the projects", response = Project.class, tags={ "technician", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Project.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "ticket not found") })
    @RequestMapping(value = "/technician/projects",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Project> getProjectsTechnician();


    @ApiOperation(value = "Logs out current logged in technician session", nickname = "logoutTechnician", notes = "", tags={ "technician", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation") })
    @RequestMapping(value = "/technician/logout",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Void> logoutTechnician();


    @ApiOperation(value = "Update a issue", nickname = "updateTechnician", notes = "This can only be done by the logged in admin with the role of technician.", tags={ "technician", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation"),
        @ApiResponse(code = 400, message = "Invalid ticket supplied"),
        @ApiResponse(code = 404, message = "Ticket not found") })
    @RequestMapping(value = "/technician/project/ticket/{ticketId}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateTechnician(@ApiParam(value = "issue that need to be updated",required=true) @PathVariable("ticketId") String ticketId,@ApiParam(value = "Updated ticket object" ,required=true )  @Valid @RequestBody Ticket body);

}
